import type { MemberForm } from '@/types/ui/members';

export const TEST_MEMBER_FORM: MemberForm = {
  surname: 'Smith',
  first_name: 'John',
  middle_name: 'Robert',
  name_extension: 'Jr',
  date_of_birth: '2001-01-15',
  place_of_birth: 'New York',
  date_hired: '2020-05-10',
  department: 'Sales',
  position: 'Manager',
  employee_no: '12345',
  tin_no: '67890',
  email_address: 'john.smith@example.com',
  member_at: '2001-01-15',
  gender: 'male',
  telephone_number: '6666',
  mobile_number: '12121212',
  beneficiaries: [
    {
      name: 'Mary Smith',
      birthdate: '1985-03-20',
      relationship: 'Spouse',
    },
    {
      name: 'Emma Smith',
      birthdate: '2010-08-05',
      relationship: 'Child',
    },
  ],
  present_address: {
    house_block_lot: '123 Main St.',
    street: 'Downtown Ave.',
    subdivision_village: 'Green Valley',
    barangay: 'Central',
    city_municipality: 'Metropolis',
    province: 'State',
    zip_code: '12345',
    residency_status: 'owned',
  },
  permanent_address: {
    house_block_lot: '456 Elm St.',
    street: 'Uptown Ave.',
    subdivision_village: 'Blue Ridge',
    barangay: 'North',
    city_municipality: 'Metropolis',
    province: 'State',
    zip_code: '67890',
  },
  father: {
    surname: 'Smith Sr.',
    first_name: 'Robert',
    middle_name: 'James',
    name_extension: 'Sr',
    date_of_birth: '1960-05-25',
    occupation: 'Retired',
    contact_number: '555-555-5555',
    type: 'Father',
  },
  mother: {
    surname: 'Smith',
    first_name: 'Mary',
    middle_name: 'Ann',
    name_extension: '',
    date_of_birth: '1962-09-15',
    occupation: 'Homemaker',
    contact_number: '555-555-5556',
    type: 'Mother',
  },
  spouse: {
    surname: 'Smith',
    first_name: 'Mary',
    middle_name: 'Elizabeth',
    name_extension: '',
    date_of_birth: '1985-03-20',
    occupation: 'Teacher',
    contact_number: '555-555-5557',
    type: 'Spouse',
  },
};
