import type { LoanApplicationPayload } from '@/types/api/loans';
import type { Loan, LoanForm, LoanTermForm } from '@/types/ui/loans';
import moment from 'moment';
import { DATE_FORMAT_DB } from '..';

export function mapLoanFormToPayload(loanForm: LoanForm): LoanApplicationPayload {
  const {
    member_id,
    contact_number,
    age,
    civil_status,
    present_address,
    home_address,
    valid_id,
    tin_number,
    number_of_children,
    application_type,
    employer_name,
    occupation,
    work_address,
    loan_purpose,
    applied_amount,
    principal_amount,
    loan_term,
    applied_date,
    released_date,
    ...rest // Extract other properties
  } = loanForm;

  const loanTerm: LoanTermForm = {
    disbursed_channel: loan_term?.disbursed_channel || null,
    interest_method: loan_term?.interest_method || null,
    interest_type: loan_term?.interest_type || null,
    loan_interest: loan_term?.loan_interest || null,
    loan_interest_period: loan_term?.loan_interest_period || null,
    loan_duration: loan_term?.loan_duration || null,
    loan_duration_type: loan_term?.loan_duration_type || null,
    repayment_cycle: loan_term?.repayment_cycle || null,
    number_of_repayments: loan_term?.number_of_repayments || null,
    repayment_mode: loan_term?.repayment_mode || null,
  };

  return {
    member_account_id: loanForm.member_account_id || 0,
    member_id: Number(member_id || 0),
    loan_product_id: loanForm.loan_product_id || 0,
    contact_number: contact_number || null,
    age: age || null,
    civil_status: civil_status || null,
    present_address: present_address || null,
    home_address: home_address || null,
    valid_id: valid_id || null,
    tin_number: tin_number || null,
    number_of_children: number_of_children || null,
    application_type: application_type || null,
    employer_name: employer_name || null,
    occupation: occupation || null,
    work_address: work_address || null,
    loan_purpose: loan_purpose || null,
    applied_amount: applied_amount || null,
    principal_amount: principal_amount || null,
    applied_date: moment(applied_date).format(DATE_FORMAT_DB),
    released_date: moment(released_date).format(DATE_FORMAT_DB),
    ...loanTerm,
    ...rest, // Spread other properties
  };
}

export function mapLoanToLoanForm(loan: Loan): LoanForm {
  const {
    member_id,
    loan_product_id,
    member_account_id,
    status,
    contact_number,
    age,
    civil_status,
    present_address,
    email,
    home_address,
    valid_id,
    tin_number,
    number_of_children,
    application_type,
    employer_name,
    occupation,
    work_address,
    work_industry,
    loan_purpose,
    salary_range,
    applied_amount,
    applied_date,
    loan_duration,
    loan_duration_type,
    repayment_cycle,
    number_of_repayments,
    repayment_mode,
    guarantor_first_id,
    guarantor_second_id,
    principal_amount,
    interest_method,
    interest_type,
    disbursed_channel,
    loan_interest,
    loan_interest_period,
  } = loan;
  const loanTerm: LoanTermForm = {
    loan_duration,
    loan_duration_type,
    repayment_cycle,
    number_of_repayments,
    repayment_mode,
    interest_method,
    interest_type,
    disbursed_channel,
    loan_interest,
    loan_interest_period,
  };

  return {
    member_id: member_id.toString(),
    contact_number,
    age,
    civil_status,
    present_address,
    home_address,
    valid_id,
    tin_number,
    number_of_children,
    application_type,
    email,
    employer_name,
    occupation,
    work_address,
    work_industry,
    guarantor_first_id,
    guarantor_second_id,
    loan_purpose,
    salary_range,
    applied_amount: applied_amount ? parseFloat(applied_amount) : null,
    member_account_id,
    loan_product_id,
    status,
    applied_date,
    principal_amount,
    loan_term: loanTerm,
  };
}
